[package]
name = "sparkle"
version = "0.1.0"
authors = ["Evan Tatarka <evan@tatarka.me>"]
edition = "2018"

[[bin]]
name = "sparkle"
path = "src/mane.rs"

[dependencies]
nom = "5.0.1"
cranelift = "0.51.0"
cranelift-module = "0.51.0"
cranelift-faerie = "0.51.0"
cranelift-simplejit = "0.51.0"
target-lexicon = "0.9.0"

[dev-dependencies]
assert_cmd = "0.11.1"
predicates = "1.0.2"
spectral = "0.6.0"
