[package]
name = "fimpp"
version = "0.1.0"
authors = ["Evan Tatarka <evan@tatarka.me>"]
edition = "2018"

[[bin]]
name = "fimpp"

[dependencies]
nom = "5.0.1"
cranelift-module = "0.50.0"
cranelift-faerie = "0.50.0"
cranelift = "0.50.0"
target-lexicon = "0.9.0"
